env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
plugins:
  - vue
rules:
  - prettier/prettier:
      - error
      - usePrettierrc: true
